name: news_app
description: "뉴스앱"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  audioplayers: ^5.2.1
  just_audio: ^0.9.36
  dotted_border: ^3.1.0
  marquee: ^2.2.3
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/a_font/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/a_font/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/a_font/Pretendard-Light.ttf
          weight: 300
        - asset: assets/a_font/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/a_font/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/a_font/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/a_font/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/a_font/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/a_font/Pretendard-Black.ttf
          weight: 900
    
    - family: WavvePADO
      fonts:
        - asset: assets/a_font/WavvePADO-Regular (1).ttf
          weight: 400
    
    - family: HakgyoansimAllimjang
      fonts:
        - asset: assets/a_font/Hakgyoansim Allimjang TTF R.ttf
          weight: 400
        - asset: assets/a_font/Hakgyoansim Allimjang TTF B.ttf
          weight: 700
  
  assets:
    - assets/a_font/
    - assets/a_image/
    - assets/a_voice/ 